#!/bin/bash
#
# Blueprint command shortcut
# Learn more @ blueprint.zip

export BLUEPRINT__FOLDER="BLUEPRINT_FOLDER_HERE"

# Only runs when sourced
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    export BLUEPRINT__PROFILE="available"
    source "$BLUEPRINT__FOLDER/blueprint.sh"
    return 0
fi

# Run Blueprint command
[[ "$EUID" == 0 ]] || exec sudo -s "$0" "$@"
bash "$BLUEPRINT__FOLDER/blueprint.sh" -bash $@
