#!/bin/bash
#
# Blueprint command shortcut
# Learn more @ blueprint.zip

# Only runs when sourced
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    export BLUEPRINT__FOLDER="BLUEPRINT_FOLDER_HERE"
    source "$BLUEPRINT__FOLDER/blueprint.sh"
    return 0
fi

# Runs the Blueprint script
exec sudo -s <<'END_OF_SUDO'

    bash BLUEPRINT_FOLDER_HERE/blueprint.sh -bash $@

END_OF_SUDO
